name: Event Loggger
on:
  push:
    branches: ['release']

jobs:
  log-github-event-goodies:
    name: 'LOG Everything on GitHub Event'
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'generate log') }}
    steps:
      - name: Logging
        run: |
          echo "TOKEN:: ${{toJSON(github)}}"
