name: Publish package to Github package

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  publish-gpr:
    if: ${{ contains(github.event.pusher.name, 'data-govtech') }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@data-govtech'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
